### PR TITLE
Fix to 3D plane when x and y are free symbols

### PR DESCRIPTION
**Pull request by Chrillebon**
Bug found:

plot_geometry(Plane(p,n))

when the free parameters are x and y and the plane does not intersect x=0, y=0. The problem narrowed down to "PlaneSeries.get_data()".

### CODE REVIEW

**Comment by Davide-sd** [comment]
Hello @Chrillebon ,

can you please clarify with an example what's wrong?

**Comment by Chrillebon** [comment]
Hi Davide,

Great to hear from you! Really good work on spb, and thank you for being so
quick to respond.

Yes, I did not quite have time to put together an example, why I saved it
as a draft. I will put together an example, and finalize the PR soon.

Merry Christmas.

**Comment by Chrillebon** [comment]
[spb_plot_plane_error.zip](https://github.com/Davide-sd/sympy-plot-backends/files/10299960/spb_plot_plane_error.zip)

Files with examples showing how the current code "fails". The "mistake" lies in the plane not intersecting the point that it is made from. "Mistake" is only present when the free variables are both x and y.

The updated code fixes this.

**Comment by Davide-sd** [comment]
@Chrillebon Thank you very much for spotting this error and taking the time to implement a fix! I'll probably merge this PR tomorrow. In the meantime I'm going to think about how to implement tests for this. Thanks again, and merry merry Christmas! :)

**Pull request merged**
